#!/bin/bash

# Tesla Investment Platform - Backend Deployment Guide
# This script provides instructions for deploying the backend

echo "=================================="
echo "Backend Deployment Instructions"
echo "=================================="
echo ""
echo "Your backend can be deployed to:"
echo ""
echo "1. RAILWAY (Recommended)"
echo "   - Sign up at https://railway.app"
echo "   - Connect your GitHub repository"
echo "   - Set environment variables:"
echo "     JWT_SECRET=your-secret-key"
echo "   - Railway auto-detects Node.js and runs 'npm start'"
echo "   - Your backend URL will be: https://your-app-name.up.railway.app"
echo ""
echo "2. RENDER"
echo "   - Sign up at https://render.com"
echo "   - Create a new Web Service"
echo "   - Point to your GitHub repo"
echo "   - Build command: npm install"
echo "   - Start command: npm start"
echo "   - Set environment variables"
echo ""
echo "3. HEROKU"
echo "   - Sign up at https://heroku.com"
echo "   - Install Heroku CLI"
echo "   - Run: heroku create your-app-name"
echo "   - Set env vars: heroku config:set JWT_SECRET=your-secret-key"
echo "   - Deploy: git push heroku main"
echo ""
echo "4. FLY.IO"
echo "   - Sign up at https://fly.io"
echo "   - Install flyctl"
echo "   - Run: flyctl launch"
echo "   - Set secrets: flyctl secrets set JWT_SECRET=your-secret-key"
echo "   - Deploy: flyctl deploy"
echo ""
echo "After deploying your backend:"
echo "1. Get your backend URL (e.g., https://my-backend.railway.app)"
echo "2. Update NEXT_PUBLIC_API_URL in .env.production"
echo "3. Deploy frontend to Vercel with updated env vars"
echo ""
